"""
This type stub file was generated by pyright.
"""

def encode_payload(args): # -> str:
    ...

def decode_payload(args): # -> str:
    ...

def build_argparser(): # -> ArgumentParser:
    ...

def main(): # -> None:
    ...

