"""
This type stub file was generated by pyright.
"""

class PyJWTError(Exception):
    """
    Base class for all exceptions
    """
    ...


class InvalidTokenError(PyJWTError):
    ...


class DecodeError(InvalidTokenError):
    ...


class InvalidSignatureError(DecodeError):
    ...


class ExpiredSignatureError(InvalidTokenError):
    ...


class InvalidAudienceError(InvalidTokenError):
    ...


class InvalidIssuerError(InvalidTokenError):
    ...


class InvalidIssuedAtError(InvalidTokenError):
    ...


class ImmatureSignatureError(InvalidTokenError):
    ...


class InvalidKeyError(PyJWTError):
    ...


class InvalidAlgorithmError(InvalidTokenError):
    ...


class MissingRequiredClaimError(InvalidTokenError):
    def __init__(self, claim) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


ExpiredSignature = ExpiredSignatureError
InvalidAudience = InvalidAudienceError
InvalidIssuer = InvalidIssuerError
